[project]
name = "ocr-vino"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "onnx>=1.19.0",
    "onnxscript>=0.5.0",
    "openvino-dev>=2024.6.0",
    "timm>=1.0.22",
    "ultralytics>=8.3.240",
]
